  - name: drupaldb
    engine: mysql
    vpc:
<% if $vpc_deploy_id then %>
      deploy_id: <%= $vpc_deploy_id %>
<% else %>
      vpc_name: vpc
<% end %>
<% if $environment == 'dev' then %>
    size: db.t2.medium
<% else %>
<% end %>
    storage: 5
    port: 3306
