  - name: drupaldb
    engine: mysql
    dns_sync_wait: false
    vpc:
<% if $vpc_deploy_id %>
      deploy_id: <%= $vpc_deploy_id %>
<% else %>
      vpc_name: vpc
<% end %>
    size: db.t2.medium
    storage: 5
    port: 3306
