  - name: drupaldb
    engine: mysql
    vpc:
<% if !$vpc_deploy_id then %>
      vpc_name: vpc
      subnets:
        <% (0..$azs.size-1).each do |i| %>
      - subnet_name: TieredSubnet<%= i %>Private
        <% end %>
<% else %>
      deploy_id: <%= $vpc_deploy_id %>
<% end %>
<% if $environment == 'dev' then %>
    size: db.t2.medium
<% else %>
<% end %>
    storage: 5
    port: 3306
