  - name: wordpress-demo-db
    engine: mysql
    creation_style: new
    db_family: mysql5.6
    vpc:
      vpc_name: wordpress-demo-vpc
    size: db.t2.micro
    version: 5.6.13
    storage: 5
    port: 3306
    publicly_accessible: true